sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ojaragodwin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ojaragodwin/docker-react npm run test